containerPort: 8080
livenessProbe:
  httpGet:
    path: /
    port: 8080
  failureThreshold: 1
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /
    port: 8080
  failureThreshold: 1
  periodSeconds: 10
